<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="gurenderkush" name="TestCases.Customer_Registartion" tests="19" failures="1" timestamp="09 Mar 2021 09:38:04 GMT" time="10.402" errors="4">
  <testcase name="customer_registration" time="0.776" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.579" classname="TestCases.Customer_Registartion"/>
  <testcase name="customer_registration" time="0.622" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.032" classname="TestCases.Customer_Registartion">
    <error type="java.lang.IllegalArgumentException" message="wrong number of arguments">
      <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="customer_registration" time="0.678" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.662" classname="TestCases.Customer_Registartion">
    <failure type="java.lang.AssertionError" message="expected [JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String \&quot;1983/01/01&#039;\&quot;: Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text &#039;1983/01/01&#039; could not be parsed at index 5; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String \&quot;1983/01/01\&quot;: Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text &#039;1983/01/01&#039; could not be parsed at index 5\n at [Source: (PushbackInputStream); line: 8, column: 12] (through reference chain: com.marutisuzuki.customer.dto.request.CustomerRegisterReqDto[\&quot;dob\&quot;])] but found [JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String &quot;1983/01/01&quot;: Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text &#039;1983/01/01&#039; could not be parsed at index 4; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String &quot;1983/01/01&quot;: Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text &#039;1983/01/01&#039; could not be parsed at index 4
 at [Source: (PushbackInputStream); line: 1, column: 128] (through reference chain: com.marutisuzuki.customer.dto.request.CustomerRegisterReqDto[&quot;dob&quot;])]">
      <![CDATA[java.lang.AssertionError: expected [JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String \"1983/01/01'\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '1983/01/01' could not be parsed at index 5; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String \"1983/01/01\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '1983/01/01' could not be parsed at index 5\n at [Source: (PushbackInputStream); line: 8, column: 12] (through reference chain: com.marutisuzuki.customer.dto.request.CustomerRegisterReqDto[\"dob\"])] but found [JSON parse error: Cannot deserialize value of type `java.time.LocalDate` from String "1983/01/01": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '1983/01/01' could not be parsed at index 4; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String "1983/01/01": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '1983/01/01' could not be parsed at index 4
 at [Source: (PushbackInputStream); line: 1, column: 128] (through reference chain: com.marutisuzuki.customer.dto.request.CustomerRegisterReqDto["dob"])]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.MSIL.TestUtils.Verify_Response.verify_Response_1(Verify_Response.java:36)
	at com.MSIL.API_LISTS.Cust_Regsiration_API.customer_registration_API(Cust_Regsiration_API.java:39)
	at TestCases.Customer_Registartion.invalid_customer_registration(Customer_Registartion.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="invalid_customer_registration" time="0.043" classname="TestCases.Customer_Registartion">
    <error type="java.lang.IllegalArgumentException" message="wrong number of arguments">
      <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="invalid_customer_registration" time="0.625" classname="TestCases.Customer_Registartion">
    <skipped/>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="invalid_customer_registration" time="0.055" classname="TestCases.Customer_Registartion">
    <skipped/>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="customer_registration" time="0.880" classname="TestCases.Customer_Registartion"/>
  <testcase name="customer_registration" time="0.865" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.789" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.675" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.050" classname="TestCases.Customer_Registartion">
    <error type="java.lang.IllegalArgumentException" message="wrong number of arguments">
      <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="invalid_customer_registration" time="0.591" classname="TestCases.Customer_Registartion"/>
  <testcase name="invalid_customer_registration" time="0.621" classname="TestCases.Customer_Registartion">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.MSIL.TestUtils.Verify_Response.verify_Response_1(Verify_Response.java:35)
	at com.MSIL.API_LISTS.Cust_Regsiration_API.customer_registration_API(Cust_Regsiration_API.java:39)
	at TestCases.Customer_Registartion.invalid_customer_registration(Customer_Registartion.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invalid_customer_registration -->
  <testcase name="invalid_customer_registration" time="0.591" classname="TestCases.Customer_Registartion"/>
  <testcase name="customer_registration" time="0.647" classname="TestCases.Customer_Registartion"/>
  <testcase name="customer_registration" time="0.621" classname="TestCases.Customer_Registartion"/>
</testsuite> <!-- TestCases.Customer_Registartion -->
